### ISSUE TITLE
Error: InvalidStateError: Failed to read the 'responseText'

### ISSUE THREAD

**Issue by melonsound** [open-xml-templating/pizzip#38]
when I try to get a file from an external link, this error occurs
```
Error: InvalidStateError: Failed to read the 'responseText' property from 'XMLHttpRequest': 
The value is only accessible if the object's 'responseType' is '' or 'text' (was 'arraybuffer').
```

**Comment by edi9999** [comment]
Hello @melonsound ,

Pizzip doesn't do the request itself, this is done in your code.

Here are some more details about tthis issue : 

This error occurs when you're trying to access the `responseText` property of an XMLHttpRequest object, but the `responseType` of the request has been set to 'arraybuffer' instead of '' (empty string) or 'text'.

To debug this issue, you can try the following steps:

1. Check your XMLHttpRequest setup:
   Make sure you're not setting the `responseType` to 'arraybuffer' if you intend to read the response as text. If you need the response as text, either leave the `responseType` as default (which is '') or explicitly set it to 'text'.

2. Use the correct property to access the response:
   - For text responses, use `xhr.responseText`
   - For ArrayBuffer responses, use `xhr.response`

3. If you actually need the response as an ArrayBuffer:
   Instead of trying to access `responseText`, use `response` property which will give you the ArrayBuffer.

4. If you need both text and ArrayBuffer:
   You might need to make two separate requests or handle the ArrayBuffer response and convert it to text if needed.

Here's an example of how to correctly set up the XMLHttpRequest for text response:

```javascript
let xhr = new XMLHttpRequest();
xhr.open('GET', 'your-url-here', true);
xhr.responseType = 'text';  // or leave this line out for default behavior
xhr.onload = function() {
    if (xhr.status === 200) {
        console.log(xhr.responseText);
    }
};
xhr.send();
```

And here's how you'd set it up for ArrayBuffer:

```javascript
let xhr = new XMLHttpRequest();
xhr.open('GET', 'your-url-here', true);
xhr.responseType = 'arraybuffer';
xhr.onload = function() {
    if (xhr.status === 200) {
        let arrayBuffer = xhr.response; // Note: not responseText
        // Process your arrayBuffer here
    }
};
xhr.send();
```

If you need more specific help, could you provide the relevant part of your code where you're making the XMLHttpRequest?
